### ISSUE TITLE
baremetal provisioning on a random disk

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#193]
When Mrugesh Karnik was deploying OSP with jetpack, it was failing as random disk is chosen during node provisioning. He has written a script to set the root disk to /dev/sda. We need to use this in jetpack

https://github.com/brainfunked/ops-automation/blob/master/ansible/rhosp-lab-setup/files/extract_serial_for_sda.rb#L20

**Comment by brainfunked** [comment]
That be me.

The symptoms for the problem are as follows:
1. Introspection works fine, nodes are made available.
2. When the nodes are provisioned, even provisioning works and `openstack stack list` will show a successfully provisioned stack.
3. However, one or more of the nodes can't be reached over the ctlplane IP.
4. When looked at through the bare metal console (iDRAC etc.), the unreachable node can be seen to have booted into its original OS, rather than the undercloud provisioned OS.

I faced this problem while doing a vanilla deployment following RHOSP director installation documentation as well. Eventually, I found this document which has multiple explicit warnings about setting the root device: https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/deployment/install_overcloud.html#register-nodes

After setting the root device after introspection, the deployment has worked perfect each time (at least three).

The script linked to uses the introspection data which provides the unique serial number for "/dev/sda" on the node. This serial number is then used to explicitly set a root device for each node.
