### ISSUE TITLE
badfish source location

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/jetpack#194]
badfish.py location changed https://github.com/redhatperformance/badfish/blob/master/src/badfish/badfish.py

We need to fix badfish related stuff in 
https://github.com/redhat-performance/jetpack/blob/master/setup_undercloud.yml

**Comment by masco** [comment]
@smalleni what you mean by source location? git repo?
if it is git repo, I didn't see any change. we are cloning from https://github.com/redhat-performance/badfish.git still it is accessible for me.
the link you shared is not accessible since the "-" is missing in the git account name.

**Comment by venkataanil** [comment]
@masco badfish.py moved to src directory. So we need to call as
./src/badfish.py -H mgmt-your-server.example.com -u root -p yourpass --reboot-only
instead of
./badfish.py -H mgmt-your-server.example.com -u root -p yourpass --reboot-only

https://github.com/redhat-performance/badfish/commit/695716abd2e93e94eace98bf1c1aeb4506aed923#diff-04c6e90faac2675aa89e2176d2eec7d8R185

**Comment by smalleni** [comment]
Or change the chdir in that ansible task ;)

**Comment by masco** [comment]
fixed and the PR is merged!
